version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: auth_cluster
    volumes:
      - auth_cluster:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: "CMD-SHELL pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
 
  
volumes:
  auth_cluster:
    name: auth_cluster